public class CartPojo {
integer qty;
    String name;
    integer cost;
    integer total;
    
    public integer getqty() {
		return this.qty;
	}

	public void setqty(integer qty) {
		this.qty = qty;
	}
    public String getname() {
		return this.name;
	}

	public void setname(String name) {
		this.name = name;    
	}
    
    
	public integer gettotal() {
		return this.total;
	}

	public void settotal(integer total) {
		this.total = total;
	}
	
}